# Generated by Django 4.2.1 on 2023-05-30 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_project_projectlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='question_text',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='projectlink',
            old_name='choice_text',
            new_name='project_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='projectlink',
            name='question',
        ),
        migrations.AddField(
            model_name='projectlink',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='base.project'),
            preserve_default=False,
        ),
    ]
