# Generated by Django 4.2.1 on 2023-05-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_question_text_project_project_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlink',
            name='votes',
        ),
    ]
