# Generated by Django 4.2.1 on 2023-05-30 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_projectlink_votes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
