# Generated by Django 4.2.1 on 2023-05-30 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlink',
            name='link',
        ),
    ]
