# Generated by Django 4.2.1 on 2023-05-30 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_projectlink_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlink',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='base.project'),
            preserve_default=False,
        ),
    ]
