# Generated by Django 4.2.1 on 2023-05-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_stufflink'),
    ]

    operations = [
        migrations.AddField(
            model_name='stufflink',
            name='thing_text',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
