# Generated by Django 4.2 on 2023-06-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_experience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
