# Generated by Django 4.2 on 2023-06-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlink',
            name='link_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
