# Generated by Django 4.2 on 2023-06-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_infotext_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='exptype',
            field=models.CharField(choices=[('Volunteer', 'Work')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
