# Generated by Django 4.2 on 2023-06-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_experience_exptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='exptype',
            field=models.CharField(choices=[('Work', 'Work'), ('Volunteer', 'Volunteer')], max_length=200),
        ),
    ]
