# Generated by Django 4.2 on 2023-06-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_experience_exptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='exptype',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Volunteer', 'Volunteer')], max_length=200),
        ),
    ]
