# Generated by Django 4.2 on 2023-06-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_profileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
