# Generated by Django 4.2 on 2023-06-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_profileinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
