# Generated by Django 4.2.4 on 2024-02-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_experience_category_alter_projectlink_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='exptype',
        ),
    ]
