# Generated by Django 4.2.4 on 2024-02-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_project_sort_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencecategory',
            name='sort_id',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
