# Generated by Django 4.2.4 on 2024-02-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_experiencecategory_sort_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('sort_id', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='projecttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projecttypes', to='base.projectcategory'),
        ),
    ]
